<?php

namespace App\Form;

use App\Entity\ProfilClub;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DescriptionFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('LogoClub', FileType::class, array(
        ))
            ->add('DescriptionClub', TextareaType::class, [
                'attr'=> [
                    'placeholder'=>'Description',
                    'class' => 'green-input']
            ])
        ;
        $options=null; // TODO: Change the autogenerated stub
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver
            ->setDefaults([
                'data_class' => ProfilClub::class
            ]); // TODO: Change the autogenerated stub
    }
}
